services:
  backend:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=GoEngineer123
    ports:
      - "5432:5432"   
    volumes:
      - ./StarWarsModels/DB-Init-Script:/docker-entrypoint-initdb.d
      - ./StarWarsModels/DB-Init-Backup:/data 

  starwars:
    image: ${DOCKER_REGISTRY-}starwars
    build:
      context: .
      dockerfile: StarWars/Dockerfile